<?php
    include("include/principal/header.php");
?>
<body>
    <?php
    include("include/principal/vinos.php");
    include("include/principal/slider.php");
    include("include/principal/testimonials.php");
    include("include/principal/footer.php");
    ?>
</body>