-- Active: 1681022712039@@db.hijaeegxjbuivzckpijg.supabase.co@5432@postgres

-- TABLAS

CREATE TABLE IF NOT EXISTS secciones (
    ID       BIGSERIAL PRIMARY KEY,
    nombre   TEXT      NOT NULL,
    activo   BOOLEAN   NOT NULL DEFAULT false,
    id_unica INTEGER   UNIQUE
);

CREATE TABLE IF NOT EXISTS usuarios (
    ID       BIGSERIAL PRIMARY KEY,
    usuario  character varying(50),
    clave    character varying(100),
    nombre   character varying(50),
    apellido character varying(50),
    email    character varying(100),
    rol      character varying(20)
);


CREATE TABLE IF NOT EXISTS paises (
    ID   BIGSERIAL PRIMARY KEY,
    pais TEXT
);

CREATE TABLE IF NOT EXISTS variedades (
    ID          SERIAL  PRIMARY KEY,
    variedad    TEXT   ,
    pais_origen INTEGER,
    Foreign     Key     (pais_origen) REFERENCES paises(ID)
);

CREATE TABLE IF NOT EXISTS vinos (
    ID                  BIGSERIAL PRIMARY KEY,          -- id: Identificador único generado automáticamente por la base de datos para cada registro en la tabla
    nombre              VARCHAR(255) NOT NULL,          -- nombre: Nombre del vino, cadena de caracteres de longitud máxima de 255
    variedad            INTEGER,                        -- variedad: Variedad de uva utilizada para elaborar el vino, cadena de caracteres de longitud máxima de 255
    anada               INTEGER,                        -- anada: Año de cosecha de la uva utilizada para elaborar el vino, número entero
    bodega              VARCHAR(255) NOT NULL,          -- bodega: Nombre de la bodega o viñedo que produce el vino, cadena de caracteres de longitud máxima de 255
    pais                INTEGER,                        -- pais: País de origen del vino, referenciamos con foreign key
    region              VARCHAR(255) NOT NULL,          -- region: Región vinícola donde se produce el vino, cadena de caracteres de longitud máxima de 255
    precio              NUMERIC(10, 2),                 -- precio: Precio del vino, número decimal con una precisión de 10 dígitos y una escala de 2 dígitos
    stock               INTEGER,                        -- stock: Cantidad de botellas del vino que están disponibles en el inventario, número entero
    tipo                VARCHAR(255),                   -- tipo: Tipo de vino (tinto, blanco, rosado, etc.), cadena de caracteres de longitud máxima de 255
    nivel_alcohol       NUMERIC(3, 1),                  -- nivel_alcohol: Porcentaje de alcohol del vino, número decimal con una precisión de 3 dígitos y una escala de 1 dígito
    tipo_barrica        VARCHAR(255),                   -- tipo_barrica: Tipo de barrica en la que se ha criado el vino (roble americano, roble francés, etc.), cadena de caracteres de longitud máxima de 255
    descripcion         TEXT,                           -- descripcion: Descripción del vino, campo de texto 
    notas_cata          TEXT,                           -- notas_cata: Descripción de las características de sabor, aroma, color y cuerpo del vino, campo de texto
    temperatura_consumo VARCHAR(255),                   -- temperatura_consumo: Temperatura recomendada para servir el vino, cadena de caracteres de longitud máxima de 255
    maridaje            TEXT,                           -- maridaje: Lista de platos recomendados para maridar con el vino, campo de texto
    id_categoria        INTEGER,                        -- id_categoria: Identificador de la categoría a la que pertenece el vino, número entero
    activo              BOOLEAN NOT NULL DEFAULT false, -- activo: Indica si el vino está activo o no, booleano con valor por defecto de false
    id_unica            INTEGER,                        -- id_unica: Identificador del vino, número entero
    url_imagen          TEXT,                           -- url_imagen: url que indica donde esta ubicada la imagen respectiva
    promocion           BOOLEAN NOT NULL DEFAULT false, -- promocion: Indica si el vino está en promoción o no, booleano con valor por defecto de false
    busqueda            INTEGER,                        -- busqueda: se genera un identficador para ubicar los productos dentro de la seccion cuando se hace una busqueda

    -- Este código crea tres restricciones de clave externa en una tabla de base de datos para asegurar que los valores ingresados en tres columnas específicas existan previamente en otras tablas. Esto ayuda a mantener la integridad y consistencia de los datos en la base de datos.
    Foreign Key (variedad    ) REFERENCES variedades(ID),
    Foreign Key (pais        ) REFERENCES paises    (ID),
    Foreign Key (id_categoria) REFERENCES secciones (ID)
);

--DATA

INSERT INTO secciones 
    (nombre                            , activo , id_unica) VALUES
    ('NUESTROS VINOS MAS VENDIDOS'     , TRUE   , 1),
    ('NUESTROS MEJORES VINOS'          , TRUE   , 2),
    ('VINOS IMPORTADOS MAS EXQUISITOS' , TRUE   , 3),
    ('RESULTADOS DE LA BUSQUEDA'       , TRUE   , 4);

INSERT INTO usuarios 
    (usuario    , clave     , nombre     , apellido  , email                        , rol               ) VALUES
    ('persona_1', '12345678', 'tienda'   , 'online'  , 'tienda@online.com'          , 'Administrador'   ),
    ('persona_2', '12345678', 'Elizabeth', 'Gottlieb', 'Schuyler.Cronin@hotmail.com', 'UsuarioCorriente');

INSERT INTO paises 
    (pais       ) VALUES
    ('Argentina'),
    ('Colombia' ),
    ('Chile'    ),
    ('España'   ),
    ('Italia'   ),
    ('Francia'  );

INSERT INTO variedades 
    (variedad            , pais_origen) VALUES
    ('Cabernet Franc'    , 6),
    ('Cabernet Sauvignon', 6),
    ('Carménère'         , 3),
    ('Malbec'            , 6),
    ('Merlot'            , 6),
    ('Pinot Grigio'      , 5),
    ('Tempranillo'       , 4);

INSERT INTO vinos 
-- (nombre                       , variedad, anada, bodega                                       , pais, region                  , precio , stock, tipo     , nivel_alcohol, tipo_barrica                                                                                         , descripcion                                                                                                                                                                                                                                                       , notas_cata                                                                                                                                                                                                                                                                                                                                              , temperatura_consumo, maridaje                                                                                                  , id_categoria, activo, id_unica , url_imagen                                                                            ,promocion, busqueda) VALUES
    (nombre, variedad, anada, bodega, pais, region, precio , stock, tipo, nivel_alcohol, tipo_barrica, descripcion, notas_cata, temperatura_consumo, maridaje, id_categoria, activo, id_unica , url_imagen,promocion, busqueda) VALUES
    ('Petirrojo'                  , 5       , 2019 , 'Bodega Requingua, Chile'                    , 3   , 'Valle Central'         , 11.99  , 40   , 'Tinto'  , 13.0         , 'El vino Petirrojo se añeja en barricas de roble francés y americano durante un periodo de 8 meses.' ,'Un vino con cuerpo y personalidad única. Sus notas frutales y especiadas te transportarán a un bosque encantado, mientras que su elegante estructura te cautivará en cada sorbo.'                                                                                 , 'En nariz, este vino chileno ofrece una mezcla de frutas rojas, especias y notas florales. En boca, se destaca por su buena acidez y cuerpo medio, con sabores de cerezas, ciruelas y un toque de vainilla. El final es largo y persistente, con un ligero toque de taninos.'                                                                           , '16-18°C'          , 'Va muy bien con platos de pasta con salsa de tomate, carnes asadas y quesos suaves.'                     , 1           , true  , 245726   , 'https://hijaeegxjbuivzckpijg.supabase.co/storage/v1/object/public/images/245726.png' ,false    , 4),
    ('Posta Pizzella'             , 4       , 2019 , 'Bodega La Posta, Argentina'                 , 1   , 'Valle de Uco, Mendoza' , 22.99  , 50   , 'Tinto'  , 13.5         , 'Este vino se añeja en barricas de roble francés y americano durante un periodo de 12 meses.'        ,'Descubre la esencia de los viñedos argentinos en cada botella de este vino. Con su aroma seductor y su sabor intenso a frutas maduras, Posta Pizzella te invita a disfrutar de una experiencia verdaderamente indulgente.'                                        , 'De origen argentino, este vino tinto presenta un intenso aroma a frutos negros, junto con notas especiadas y de vainilla. En el paladar, es un vino de cuerpo medio con taninos suaves y redondos, con un sabor a frutos negros maduros y una acidez equilibrada. El final es largo y agradable.'                                                      , '16-18°C'          , 'Es ideal para acompañar con carnes rojas a la parrilla, guisos y estofados.'                             , 1           , true  , 933404   , 'https://hijaeegxjbuivzckpijg.supabase.co/storage/v1/object/public/images/933404.png' ,false    , 4),
    ('Marquez de villa de leyva'  , 2       , 2017 , 'Bodega Marquez de Villa de Leyva, Colombia' , 2   , 'Villa de Leyva'        , 25.99  , 50   , 'Tinto'  , 13.5         , 'Este vino se añeja en barricas de roble francés durante un periodo de 12 meses.'                    ,'Un vino que rinde homenaje a la tradición y la historia. Marquez de Villa de Leyva te sorprenderá con su equilibrio perfecto entre notas de frutas negras, especias y un toque sutil de roble, creando una experiencia memorable.'                                , 'Proveniente de Colombia, este vino tinto tiene un aroma a frutos rojos y negros, junto con notas de cedro y especias. En el paladar, es un vino de cuerpo medio con taninos suaves y una acidez equilibrada, con sabores a frutos negros y un toque de vainilla. El final es largo y persistente.'                                                     , '15-17°C'          , 'Combina bien con platos de pollo asado, pastas con salsas cremosas y quesos suaves.'                     , 1           , true  , 948930   , 'https://hijaeegxjbuivzckpijg.supabase.co/storage/v1/object/public/images/948930.png' ,false    , 4),
    ('Don Melchor'                , 2       , 2018 , 'Bodega Concha y Toro, Chile'                , 3   , 'Maipo'                 , 125.99 , 50   , 'Tinto'  , 14.0         , 'Este vino se añeja en barricas de roble francés durante un periodo de 15 meses.'                    ,'La excelencia en cada detalle define a Don Melchor. Este vino de renombre internacional ofrece una combinación armoniosa de frutas negras, taninos sedosos y un final largo y persistente que deleitará a los amantes del buen vino.'                             , 'Este vino chileno ofrece un aroma a frutos rojos maduros, junto con notas de tabaco y cuero. En boca, es un vino de cuerpo completo con taninos firmes y una acidez equilibrada, con sabores a frutos negros y un toque de vainilla. El final es largo y persistente, con un ligero toque de especias.'                                                , '16-18°C'          , 'Va muy bien con carnes rojas asadas, platos de cordero y quesos curados.'                                , 1           , true  , 543152   , 'https://hijaeegxjbuivzckpijg.supabase.co/storage/v1/object/public/images/543152.png' ,false    , 4),
    ('Purple Angel'               , 3       , 2018 , 'Bodega Montes, Chile'                       , 3   , 'Colchagua Valley'      , 45.99  , 50   , 'Tinto'  , 14.5         , 'Este vino se añeja en barricas de roble francés durante un periodo de 18 meses.'                    ,'Sumérgete en la tentación de Purple Angel. Sus aromas intensos a frutas rojas y negras, complementados con notas de chocolate y vainilla, te envolverán en una experiencia sensual y llena de placer.'                                                            , 'Originario de Chile, este vino tinto presenta un aroma a frutos negros, junto con notas de especias y cedro. En el paladar, es un vino de cuerpo completo con taninos firmes y una acidez equilibrada, con sabores a frutos negros maduros y un toque de vainilla y chocolate oscuro. El final es largo y persistente, con un ligero toque de tabaco.' , '16-18°C'          , 'Es ideal para acompañar con carnes rojas asadas, platos de caza y quesos fuertes.'                       , 1           , true  , 330628   , 'https://hijaeegxjbuivzckpijg.supabase.co/storage/v1/object/public/images/330628.png' ,false    , 4),
    ('Muga'                       , 6       , 2016 , 'Bodegas Muga, España'                       , 4   , 'Rioja'                 , 29.99  , 50   , 'tinto'  , 14.0         , 'Este vino se añeja en barricas de roble francés y americano durante un periodo de 24 meses.'        ,'El equilibrio perfecto entre tradición y modernidad se encuentra en cada botella de Muga. Disfruta de su elegante carácter con notas de frutas rojas, vainilla y un toque especiado, que te transportará a los paisajes encantadores de La Rioja, España.'        , 'Este vino español tiene un aroma a frutos rojos y negros, junto con notas de cuero y especias. En boca, es un vino de cuerpo medio con taninos suaves y una acidez equilibrada, con sabores a frutos negros y un toque de vainilla. El final es largo y persistente, con un ligero toque de regaliz.'                                                  , '16-18°C'          , 'Va muy bien con platos de jamón ibérico, embutidos y carnes asadas.'                                     , 2           , true  , 692159   , 'https://hijaeegxjbuivzckpijg.supabase.co/storage/v1/object/public/images/692159.png' ,false    , 4),
    ('Reserva de la Tierra'       , 2       , 2015 , 'Bodegas Fariña, España'                     , 3   , 'Valle del Maipo'       , 19.99  , 100  , 'tinto'  , 13.5         , 'Este vino se añeja en barricas de roble francés durante un periodo de 12 meses.'                    ,'Este vino encarna la esencia de la tierra en cada sorbo. Con sus aromas a frutas maduras y su suave textura, Reserva de la Tierra te llevará a un viaje sensorial por los paisajes vírgenes y exuberantes de los viñedos.'                                        , 'Proveniente de Colombia, este vino tinto tiene un aroma a frutos rojos y negros, junto con notas de vainilla y especias. En el paladar, es un vino de cuerpo medio con taninos suaves y una acidez equilibrada, con sabores a frutos negros maduros y un toque de regaliz. El final es largo y agradable.'                                             , '18-20°C'          , 'Combina bien con platos de carne de cerdo asada, carnes rojas a la parrilla y quesos curados.'           , 2           , true  , 323324   , 'https://hijaeegxjbuivzckpijg.supabase.co/storage/v1/object/public/images/323324.png' ,false    , 4),
    ('Maison Castel Gran Reserva' , 6       , 2015 , 'Maison Castel, Francia'                     , 4   , 'Cariñena'              , 19.99  , 80   , 'tinto'  , 13.5         , 'Este vino se añeja en barricas de roble francés durante un periodo de 12 meses.'                    ,'Descubre la elegancia francesa en cada botella de este gran reserva. Su complejidad aromática, con notas de frutas maduras, madera y especias, te invita a disfrutar de momentos inolvidables junto a tus seres queridos.'                                        , 'Este vino francés ofrece un aroma a frutos rojos y negros, junto con notas de especias y vainilla. En boca, es un vino de cuerpo completo con taninos firmes y una acidez equilibrada, con sabores a frutos negros y un toque de cacao y café. El final es largo y persistente.'                                                                       , '18-20°C'          , 'Es ideal para acompañar con platos de caza, carnes rojas a la parrilla y quesos curados.'                , 2           , true  , 191880   , 'https://hijaeegxjbuivzckpijg.supabase.co/storage/v1/object/public/images/191880.png' ,false    , 4),
    ('Santa Margherita'           , 6       , 2020 , 'Santa Margherita, Italia'                   , 5   , 'Alto Adige'            , 21.99  , 120  , 'blanco' , 12.0         , 'Este vino no se añeja en barricas de roble.'                                                        ,'Un vino italiano que captura la esencia del sol y el mar Mediterráneo. Santa Margherita te brinda una experiencia refrescante con sus notas cítricas y florales, su acidez equilibrada y su final vibrante.'                                                      , 'De origen italiano, este vino tinto tiene un aroma a frutos rojos maduros, junto con notas de vainilla y especias. En el paladar, es un vino de cuerpo medio con taninos suaves y una acidez equilibrada, con sabores a frutos rojos y un toque de cacao. El final es largo y agradable.'                                                              , '12-14°C'          , 'Va muy bien con platos de pescados y mariscos, ensaladas y quesos suaves.'                               , 2           , true  , 257609   , 'https://hijaeegxjbuivzckpijg.supabase.co/storage/v1/object/public/images/257609.png' ,false    , 4),
    ('Montes Alpha M'             , 2       , 2017 , 'Bodega Montes, Chile'                       , 3   , 'Valle de Colchagua'    , 49.99  , 40   , 'tinto'  , 14.5         , 'Este vino se añeja en barricas de roble francés durante un periodo de 18 meses.'                    ,'Un vino chileno que encarna la pasión y la sofisticación. Montes Alpha M te seducirá con sus aromas a frutas negras, chocolate y tabaco, mientras sus taninos firmes y su elegante estructura te envuelven en un abrazo cálido.'                                  , 'Este vino chileno ofrece un aroma a frutos rojos y negros, junto con notas de especias y tabaco. En boca, es un vino de cuerpo completo con taninos firmes y una acidez equilibrada, con sabores a frutos negros y un toque de vainilla. El final es largo y persistente, con un ligero toque de cedro.'                                               , '18-20°C'          , 'Es ideal para acompañar con platos de carnes rojas a la parrilla, guisos y estofados.'                   , 2           , true  , 782699   , 'https://hijaeegxjbuivzckpijg.supabase.co/storage/v1/object/public/images/782699.png' ,false    , 4),
    ('Angelica Zapata'            , 4       , 2016 , 'Bodega Catena Zapata, Argentina'            , 1   , 'Mendoza'               , 54.99  , 20   , 'tinto'  , 14.5         , 'Este vino se añeja en barricas de roble francés durante un periodo de 18 meses.'                    ,'La expresión máxima de la viticultura argentina se encuentra en Angelica Zapata. Este vino de alta gama te sorprenderá con sus notas complejas a frutas maduras, especias y tabaco, creando una experiencia única y memorable.'                                   , 'De origen argentino, este vino tinto presenta un aroma a frutos negros y notas de especias y tabaco. En el paladar, es un vino de cuerpo completo con taninos firmes y una acidez equilibrada, con sabores a frutos negros maduros y un toque de vainilla y chocolate oscuro. El final es largo y persistente.'                                        , '16-18°C'          , 'Va muy bien con platos de carnes rojas asadas, platos de caza y quesos curados.'                         , 3           , true  , 850550   , 'https://hijaeegxjbuivzckpijg.supabase.co/storage/v1/object/public/images/850550.png' ,false    , 4),
    ('Gran Enemigo'               , 1       , 2012 , 'Bodega Catena Zapata, Argentina'            , 1   , 'Mendoza'               , 149.99 , 10   , 'tinto'  , 14.5         , 'Este vino se añeja en barricas de roble francés durante un periodo de 18 meses.'                    ,'Un vino que desafía las convenciones y rompe barreras. Gran Enemigo combina la elegancia del Viejo Mundo con la audacia del Nuevo Mundo, ofreciendo un perfil aromático y gustativo sorprendente que despierta los sentidos.'                                     , 'Este vino argentino tiene un aroma a frutos negros y notas de especias y cedro. En boca, es un vino de cuerpo completo con taninos firmes y una acidez equilibrada, con sabores a frutos negros y un toque de vainilla. El final es largo y persistente, con un ligero toque de tabaco.'                                                               , '16-18°C'          , 'Es ideal para acompañar con carnes rojas asadas, platos de caza y quesos fuertes.'                       , 3           , true  , 652132   , 'https://hijaeegxjbuivzckpijg.supabase.co/storage/v1/object/public/images/652132.png' ,false    , 4),
    ('Zuccardi Serie A'           , 4       , 2019 , 'Bodega Familia Zuccardi, Argentina'         , 1   , 'Valle de Uco'          , 17.99  , 80   , 'tinto'  , 14.0         , 'Este vino se añeja en barricas de roble francés durante un periodo de 10 meses.'                    ,'Este vino argentino captura la esencia de los viñedos de alta altitud. Zuccardi Serie A te cautivará con su frescura y vivacidad, sus notas frutales y herbáceas, y su textura sedosa que lo convierten en una opción ideal para acompañar cualquier ocasión.'    , 'Proveniente de Argentina, este vino tinto presenta un aroma a frutos rojos y negros, junto con notas de especias y vainilla. En el paladar, es un vino de cuerpo medio con taninos suaves y una acidez equilibrada, con sabores a frutos negros y un toque de regaliz. El final es largo y agradable.'                                                 , '16-18°C'          , 'Va muy bien con platos de carnes rojas a la parrilla, guisos y estofados.'                               , 3           , true  , 438553   , 'https://hijaeegxjbuivzckpijg.supabase.co/storage/v1/object/public/images/438553.png' ,false    , 4),
    ('Cerro Verde'                , 4       , 2017 , 'Bodegas Fariña, España'                     , 1   , 'Mendoza'               , 26.99  , 40   , 'tinto'  , 14.0         , 'Este vino se añeja en barricas de roble francés durante un periodo de 10 meses.'                    ,'Un vino que celebra la riqueza y diversidad de los suelos latinoamericanos. Cerro Verde te envolverá con sus aromas intensos a frutas rojas y negras, su textura aterciopelada y su final persistente, transportándote a los majestuosos paisajes de los viñedos.', 'Este vino chileno tiene un aroma a frutos rojos y negros, junto con notas de vainilla y especias. En boca, es un vino de cuerpo medio con taninos suaves y una acidez equilibrada, con sabores a frutos negros maduros y un toque de chocolate oscuro. El final es largo y agradable.'                                                                 , '16-18°C'          , 'Es ideal para acompañar con platos de carne de cerdo asada, carnes rojas a la parrilla y quesos suaves.' , 3           , true  , 178631   , 'https://hijaeegxjbuivzckpijg.supabase.co/storage/v1/object/public/images/178631.png' ,false    , 4),
    ('Codice'                     , 4       , 2018 , 'Bodegas y Viñedos Codice, Argentina'        , 1   , 'Mendoza'               , 23.99  , 80   , 'tinto'  , 13.5         , 'Este vino se añeja en barricas de roble francés durante un periodo de 12 meses.'                    ,'Descubre la esencia de la pasión y la historia en cada botella de Codice. Con sus notas a frutas maduras, su elegancia y su equilibrio perfecto, este vino te invita a disfrutar de una experiencia sensorial única que cautivará tus sentidos.'                  , 'De origen argentino, este vino tinto presenta un aroma a frutos rojos y negros, junto con notas de especias y cedro. En el paladar, es un vino de cuerpo medio con taninos suaves y una acidez equilibrada, con sabores a frutos negros y un toque de vainilla. El final es largo y agradable.'                                                        , '16-18°C'          , 'Va muy bien con platos de carnes rojas a la parrilla, guisos y estofados.'                               , 3           , true  , 265178   , 'https://hijaeegxjbuivzckpijg.supabase.co/storage/v1/object/public/images/265178.png' ,false    , 4);