-- Active: 1685292224953@@db.hijaeegxjbuivzckpijg.supabase.co@5432@postgres@public

-- TABLAS

CREATE TABLE IF NOT EXISTS secciones (
    ID       BIGSERIAL PRIMARY KEY,
    nombre   TEXT      NOT NULL,
    activo   BOOLEAN   NOT NULL DEFAULT false,
    id_unica INTEGER   UNIQUE
);

CREATE TABLE IF NOT EXISTS paises (
    ID   BIGSERIAL PRIMARY KEY,
    pais TEXT
);

CREATE TABLE IF NOT EXISTS variedades (
    ID          SERIAL  PRIMARY KEY,
    variedad    TEXT   ,
    pais_origen INTEGER,
    Foreign     Key     (pais_origen) REFERENCES paises(ID)
);

CREATE TABLE IF NOT EXISTS vinos (
    ID                  BIGSERIAL PRIMARY KEY,          -- id: Identificador único generado automáticamente por la base de datos para cada registro en la tabla
    nombre              VARCHAR(255) NOT NULL,          -- nombre: Nombre del vino, cadena de caracteres de longitud máxima de 255
    variedad            INTEGER,                        -- variedad: Variedad de uva utilizada para elaborar el vino, cadena de caracteres de longitud máxima de 255
    anada               INTEGER,                        -- anada: Año de cosecha de la uva utilizada para elaborar el vino, número entero
    bodega              VARCHAR(255) NOT NULL,          -- bodega: Nombre de la bodega o viñedo que produce el vino, cadena de caracteres de longitud máxima de 255
    pais                INTEGER,                        -- pais: País de origen del vino, referenciamos con foreign key
    region              VARCHAR(255) NOT NULL,          -- region: Región vinícola donde se produce el vino, cadena de caracteres de longitud máxima de 255
    precio              NUMERIC(10, 3),                 -- precio: Precio del vino, número decimal con una precisión de 10 dígitos y una escala de 3 dígitos
    stock               INTEGER,                        -- stock: Cantidad de botellas del vino que están disponibles en el inventario, número entero
    tipo                VARCHAR(255),                   -- tipo: Tipo de vino (tinto, blanco, rosado, etc.), cadena de caracteres de longitud máxima de 255
    nivel_alcohol       NUMERIC(3, 1),                  -- nivel_alcohol: Porcentaje de alcohol del vino, número decimal con una precisión de 3 dígitos y una escala de 1 dígito
    tipo_barrica        VARCHAR(255),                   -- tipo_barrica: Tipo de barrica en la que se ha criado el vino (roble americano, roble francés, etc.), cadena de caracteres de longitud máxima de 255
    descripcion         TEXT,                           -- descripcion: Descripción del vino, campo de texto 
    notas_cata          TEXT,                           -- notas_cata: Descripción de las características de sabor, aroma, color y cuerpo del vino, campo de texto
    temperatura_consumo VARCHAR(255),                   -- temperatura_consumo: Temperatura recomendada para servir el vino, cadena de caracteres de longitud máxima de 255
    maridaje            TEXT,                           -- maridaje: Lista de platos recomendados para maridar con el vino, campo de texto
    id_categoria        INTEGER,                        -- id_categoria: Identificador de la categoría a la que pertenece el vino, número entero
    activo              BOOLEAN NOT NULL DEFAULT false, -- activo: Indica si el vino está activo o no, booleano con valor por defecto de false
    id_unica            INTEGER,                        -- id_unica: Identificador del vino, número entero
    url_imagen          TEXT,                           -- url_imagen: url que indica donde esta ubicada la imagen respectiva
    promocion           BOOLEAN NOT NULL DEFAULT false, -- promocion: Indica si el vino está en promoción o no, booleano con valor por defecto de false
    busqueda            INTEGER,                        -- busqueda: se genera un identficador para ubicar los productos.json dentro de la seccion cuando se hace una busqueda

    -- Este código crea tres restricciones de clave externa en una tabla de base de datos para asegurar que los valores ingresados en tres columnas específicas existan previamente en otras tablas. Esto ayuda a mantener la integridad y consistencia de los datos en la base de datos.
    Foreign Key (variedad)     REFERENCES variedades(ID),
    Foreign Key (pais)         REFERENCES paises    (ID),
    Foreign Key (id_categoria) REFERENCES secciones (ID)
);

--DATA

INSERT INTO secciones 
    (nombre                            , activo , id_unica) VALUES
    ('NUESTROS VINOS MAS VENDIDOS'     , TRUE   , 1),
    ('NUESTROS MEJORES VINOS'          , TRUE   , 2),
    ('VINOS IMPORTADOS MAS EXQUISITOS' , TRUE   , 3),
    ('RESULTADOS DE LA BUSQUEDA'       , TRUE   , 4);

INSERT INTO paises (pais)
VALUES
    ('Argentina'),
    ('Colombia'),
    ('Chile'),
    ('España'),
    ('Italia'),
    ('Francia');

INSERT INTO variedades 
(variedad, pais_origen)
VALUES
    ('Cabernet Franc', 6),
    ('Cabernet Sauvignon', 6),
    ('Carménère', 3),
    ('Malbec', 6),
    ('Merlot', 6),
    ('Pinot Grigio', 5),
    ('Tempranillo', 4),
    ('Tempranillo y Cabernet Sauvignon'),
    ('60% Pinot Noir, 25% Chardonnay y 15% Meunier'),
    ('Blanc de Blancs'),
    ('Shiraz'),
    ('Petit Verdot'),
    ('Pinot Noir'),
    ('Cabernet Sauvignon, Petit Verdot, Cabernet Franc, Merlot y Malbec');

INSERT INTO vinos 
    (nombre, variedad, anada, bodega, pais, region, precio , stock, tipo, nivel_alcohol, tipo_barrica, descripcion, notas_cata, temperatura_consumo, maridaje, id_categoria, activo, id_unica , url_imagen,promocion, busqueda) VALUES
--     (nombre                                          , variedad, anada, bodega                                       , pais            , region                  , precio  , stock, tipo     , nivel_alcohol, tipo_barrica                                                                                         , descripcion                                                                                                                                                                                                                                                         , notas_cata                                                                                                                                                                                                                                                                                                                                              , temperatura_consumo, maridaje                                                                                                  , id_categoria, activo, id_unica , url_imagen                                                                            ,promocion, busqueda ) VALUES
    ('Petirrojo'                                     , 5       , 2019 , 'Bodega Requingua, Chile'                    , 3               , 'Valle Central'         , 87.422  , 40   , 'Tinto'  , 13.0         , 'El vino Petirrojo se añeja en barricas de roble francés y americano durante un periodo de 8 meses.' , 'Un vino con cuerpo y personalidad única. Sus notas frutales y especiadas te transportarán a un bosque encantado, mientras que su elegante estructura te cautivará en cada sorbo.'                                                                                  , 'En nariz, este vino chileno ofrece una mezcla de frutas rojas, especias y notas florales. En boca, se destaca por su buena acidez y cuerpo medio, con sabores de cerezas, ciruelas y un toque de vainilla. El final es largo y persistente, con un ligero toque de taninos.'                                                                           , '16-18°C'          , 'Va muy bien con platos de pasta con salsa de tomate, carnes asadas y quesos suaves.'                     , 1           , true  , 245726   , 'https://npuxpuelimayqrsmzqur.supabase.co/storage/v1/object/public/images/245726.png' ,false    , 4        ),
    ('Posta Pizzella'                                , 4       , 2019 , 'Bodega La Posta, Argentina'                 , 1               , 'Valle de Uco, Mendoza' , 98.842  , 50   , 'Tinto'  , 13.5         , 'Este vino se añeja en barricas de roble francés y americano durante un periodo de 12 meses.'        , 'Descubre la esencia de los viñedos argentinos en cada botella de este vino. Con su aroma seductor y su sabor intenso a frutas maduras, Posta Pizzella te invita a disfrutar de una experiencia verdaderamente indulgente.'                                         , 'De origen argentino, este vino tinto presenta un intenso aroma a frutos negros, junto con notas especiadas y de vainilla. En el paladar, es un vino de cuerpo medio con taninos suaves y redondos, con un sabor a frutos negros maduros y una acidez equilibrada. El final es largo y agradable.'                                                      , '16-18°C'          , 'Es ideal para acompañar con carnes rojas a la parrilla, guisos y estofados.'                             , 1           , true  , 933404   , 'https://npuxpuelimayqrsmzqur.supabase.co/storage/v1/object/public/images/933404.png' ,false    , 4        ),
    ('Marquez de villa de leyva'                     , 2       , 2017 , 'Bodega Marquez de Villa de Leyva, Colombia' , 2               , 'Villa de Leyva'        , 477.162 , 50   , 'Tinto'  , 13.5         , 'Este vino se añeja en barricas de roble francés durante un periodo de 12 meses.'                    , 'Un vino que rinde homenaje a la tradición y la historia. Marquez de Villa de Leyva te sorprenderá con su equilibrio perfecto entre notas de frutas negras, especias y un toque sutil de roble, creando una experiencia memorable.'                                 , 'Proveniente de Colombia, este vino tinto tiene un aroma a frutos rojos y negros, junto con notas de cedro y especias. En el paladar, es un vino de cuerpo medio con taninos suaves y una acidez equilibrada, con sabores a frutos negros y un toque de vainilla. El final es largo y persistente.'                                                     , '15-17°C'          , 'Combina bien con platos de pollo asado, pastas con salsas cremosas y quesos suaves.'                     , 1           , true  , 948930   , 'https://npuxpuelimayqrsmzqur.supabase.co/storage/v1/object/public/images/948930.png' ,false    , 4        ),
    ('Don Melchor'                                   , 2       , 2018 , 'Bodega Concha y Toro, Chile'                , 3               , 'Maipo'                 , 174.622 , 50   , 'Tinto'  , 14.0         , 'Este vino se añeja en barricas de roble francés durante un periodo de 15 meses.'                    , 'La excelencia en cada detalle define a Don Melchor. Este vino de renombre internacional ofrece una combinación armoniosa de frutas negras, taninos sedosos y un final largo y persistente que deleitará a los amantes del buen vino.'                              , 'Este vino chileno ofrece un aroma a frutos rojos maduros, junto con notas de tabaco y cuero. En boca, es un vino de cuerpo completo con taninos firmes y una acidez equilibrada, con sabores a frutos negros y un toque de vainilla. El final es largo y persistente, con un ligero toque de especias.'                                                , '16-18°C'          , 'Va muy bien con carnes rojas asadas, platos de cordero y quesos curados.'                                , 1           , true  , 543152   , 'https://npuxpuelimayqrsmzqur.supabase.co/storage/v1/object/public/images/543152.png' ,false    , 4        ),
    ('Purple Angel'                                  , 3       , 2018 , 'Bodega Montes, Chile'                       , 3               , 'Colchagua Valley'      , 113.962 , 50   , 'Tinto'  , 14.5         , 'Este vino se añeja en barricas de roble francés durante un periodo de 18 meses.'                    , 'Sumérgete en la tentación de Purple Angel. Sus aromas intensos a frutas rojas y negras, complementados con notas de chocolate y vainilla, te envolverán en una experiencia sensual y llena de placer.'                                                             , 'Originario de Chile, este vino tinto presenta un aroma a frutos negros, junto con notas de especias y cedro. En el paladar, es un vino de cuerpo completo con taninos firmes y una acidez equilibrada, con sabores a frutos negros maduros y un toque de vainilla y chocolate oscuro. El final es largo y persistente, con un ligero toque de tabaco.' , '16-18°C'          , 'Es ideal para acompañar con carnes rojas asadas, platos de caza y quesos fuertes.'                       , 1           , true  , 330628   , 'https://npuxpuelimayqrsmzqur.supabase.co/storage/v1/object/public/images/330628.png' ,false    , 4        ),
    ('Muga'                                          , 6       , 2016 , 'Bodegas Muga, España'                       , 4               , 'Rioja'                 , 75.962  , 50   , 'Tinto'  , 14.0         , 'Este vino se añeja en barricas de roble francés y americano durante un periodo de 24 meses.'        , 'El equilibrio perfecto entre tradición y modernidad se encuentra en cada botella de Muga. Disfruta de su elegante carácter con notas de frutas rojas, vainilla y un toque especiado, que te transportará a los paisajes encantadores de La Rioja, España.'         , 'Este vino español tiene un aroma a frutos rojos y negros, junto con notas de cuero y especias. En boca, es un vino de cuerpo medio con taninos suaves y una acidez equilibrada, con sabores a frutos negros y un toque de vainilla. El final es largo y persistente, con un ligero toque de regaliz.'                                                  , '16-18°C'          , 'Va muy bien con platos de jamón ibérico, embutidos y carnes asadas.'                                     , 2           , true  , 692159   , 'https://npuxpuelimayqrsmzqur.supabase.co/storage/v1/object/public/images/692159.png' ,false    , 4        ),
    ('Reserva de la Tierra'                          , 2       , 2015 , 'Bodegas Fariña, España'                     , 3               , 'Valle del Maipo'       , 75.962  , 100  , 'Tinto'  , 13.5         , 'Este vino se añeja en barricas de roble francés durante un periodo de 12 meses.'                    , 'Este vino encarna la esencia de la tierra en cada sorbo. Con sus aromas a frutas maduras y su suave textura, Reserva de la Tierra te llevará a un viaje sensorial por los paisajes vírgenes y exuberantes de los viñedos.'                                         , 'Proveniente de Colombia, este vino tinto tiene un aroma a frutos rojos y negros, junto con notas de vainilla y especias. En el paladar, es un vino de cuerpo medio con taninos suaves y una acidez equilibrada, con sabores a frutos negros maduros y un toque de regaliz. El final es largo y agradable.'                                             , '18-20°C'          , 'Combina bien con platos de carne de cerdo asada, carnes rojas a la parrilla y quesos curados.'           , 2           , true  , 323324   , 'https://npuxpuelimayqrsmzqur.supabase.co/storage/v1/object/public/images/323324.png' ,false    , 4        ),
    ('Maison Castel Gran Reserva'                    , 6       , 2015 , 'Maison Castel, Francia'                     , 4               , 'Cariñena'              , 83.582  , 80   , 'Tinto'  , 13.5         , 'Este vino se añeja en barricas de roble francés durante un periodo de 12 meses.'                    , 'Descubre la elegancia francesa en cada botella de este gran reserva. Su complejidad aromática, con notas de frutas maduras, madera y especias, te invita a disfrutar de momentos inolvidables junto a tus seres queridos.'                                         , 'Este vino francés ofrece un aroma a frutos rojos y negros, junto con notas de especias y vainilla. En boca, es un vino de cuerpo completo con taninos firmes y una acidez equilibrada, con sabores a frutos negros y un toque de cacao y café. El final es largo y persistente.'                                                                       , '18-20°C'          , 'Es ideal para acompañar con platos de caza, carnes rojas a la parrilla y quesos curados.'                , 2           , true  , 191880   , 'https://npuxpuelimayqrsmzqur.supabase.co/storage/v1/object/public/images/191880.png' ,false    , 4        ),
    ('Santa Margherita'                              , 6       , 2020 , 'Santa Margherita, Italia'                   , 5               , 'Alto Adige'            , 189.962 , 120  , 'Blanco' , 12.0         , 'Este vino no se añeja en barricas de roble.'                                                        , 'Un vino italiano que captura la esencia del sol y el mar Mediterráneo. Santa Margherita te brinda una experiencia refrescante con sus notas cítricas y florales, su acidez equilibrada y su final vibrante.'                                                       , 'De origen italiano, este vino tinto tiene un aroma a frutos rojos maduros, junto con notas de vainilla y especias. En el paladar, es un vino de cuerpo medio con taninos suaves y una acidez equilibrada, con sabores a frutos rojos y un toque de cacao. El final es largo y agradable.'                                                              , '12-14°C'          , 'Va muy bien con platos de pescados y mariscos, ensaladas y quesos suaves.'                               , 2           , true  , 257609   , 'https://npuxpuelimayqrsmzqur.supabase.co/storage/v1/object/public/images/257609.png' ,false    , 4        ),
    ('Montes Alpha M'                                , 2       , 2017 , 'Bodega Montes, Chile'                       , 3               , 'Valle de Colchagua'    , 208.962 , 40   , 'Tinto'  , 14.5         , 'Este vino se añeja en barricas de roble francés durante un periodo de 18 meses.'                    , 'Un vino chileno que encarna la pasión y la sofisticación. Montes Alpha M te seducirá con sus aromas a frutas negras, chocolate y tabaco, mientras sus taninos firmes y su elegante estructura te envuelven en un abrazo cálido.'                                   , 'Este vino chileno ofrece un aroma a frutos rojos y negros, junto con notas de especias y tabaco. En boca, es un vino de cuerpo completo con taninos firmes y una acidez equilibrada, con sabores a frutos negros y un toque de vainilla. El final es largo y persistente, con un ligero toque de cedro.'                                               , '18-20°C'          , 'Es ideal para acompañar con platos de carnes rojas a la parrilla, guisos y estofados.'                   , 2           , true  , 782699   , 'https://npuxpuelimayqrsmzqur.supabase.co/storage/v1/object/public/images/782699.png' ,false    , 4        ),
    ('Angelica Zapata'                               , 4       , 2016 , 'Bodega Catena Zapata, Argentina'            , 1               , 'Mendoza'               , 569.962 , 20   , 'Tinto'  , 14.5         , 'Este vino se añeja en barricas de roble francés durante un periodo de 18 meses.'                    , 'La expresión máxima de la viticultura argentina se encuentra en Angelica Zapata. Este vino de alta gama te sorprenderá con sus notas complejas a frutas maduras, especias y tabaco, creando una experiencia única y memorable.'                                    , 'De origen argentino, este vino tinto presenta un aroma a frutos negros y notas de especias y tabaco. En el paladar, es un vino de cuerpo completo con taninos firmes y una acidez equilibrada, con sabores a frutos negros maduros y un toque de vainilla y chocolate oscuro. El final es largo y persistente.'                                        , '16-18°C'          , 'Va muy bien con platos de carnes rojas asadas, platos de caza y quesos curados.'                         , 3           , true  , 850550   , 'https://npuxpuelimayqrsmzqur.supabase.co/storage/v1/object/public/images/850550.png' ,false    , 4        ),
    ('Gran Enemigo'                                  , 1       , 2012 , 'Bodega Catena Zapata, Argentina'            , 1               , 'Mendoza'               , 68.362  , 10   , 'Tinto'  , 14.5         , 'Este vino se añeja en barricas de roble francés durante un periodo de 18 meses.'                    , 'Un vino que desafía las convenciones y rompe barreras. Gran Enemigo combina la elegancia del Viejo Mundo con la audacia del Nuevo Mundo, ofreciendo un perfil aromático y gustativo sorprendente que despierta los sentidos.'                                      , 'Este vino argentino tiene un aroma a frutos negros y notas de especias y cedro. En boca, es un vino de cuerpo completo con taninos firmes y una acidez equilibrada, con sabores a frutos negros y un toque de vainilla. El final es largo y persistente, con un ligero toque de tabaco.'                                                               , '16-18°C'          , 'Es ideal para acompañar con carnes rojas asadas, platos de caza y quesos fuertes.'                       , 3           , true  , 652132   , 'https://npuxpuelimayqrsmzqur.supabase.co/storage/v1/object/public/images/652132.png' ,false    , 4        ),
    ('Zuccardi Serie A'                              , 4       , 2019 , 'Bodega Familia Zuccardi, Argentina'         , 1               , 'Valle de Uco'          , 102.762 , 80   , 'Tinto'  , 14.0         , 'Este vino se añeja en barricas de roble francés durante un periodo de 10 meses.'                    , 'Este vino argentino captura la esencia de los viñedos de alta altitud. Zuccardi Serie A te cautivará con su frescura y vivacidad, sus notas frutales y herbáceas, y su textura sedosa que lo convierten en una opción ideal para acompañar cualquier ocasión.'     , 'Proveniente de Argentina, este vino tinto presenta un aroma a frutos rojos y negros, junto con notas de especias y vainilla. En el paladar, es un vino de cuerpo medio con taninos suaves y una acidez equilibrada, con sabores a frutos negros y un toque de regaliz. El final es largo y agradable.'                                                 , '16-18°C'          , 'Va muy bien con platos de carnes rojas a la parrilla, guisos y estofados.'                               , 3           , true  , 438553   , 'https://npuxpuelimayqrsmzqur.supabase.co/storage/v1/object/public/images/438553.png' ,false    , 4        ),
    ('Cerro Verde'                                   , 4       , 2017 , 'Bodegas Fariña, España'                     , 1               , 'Mendoza'               , 91.362  , 40   , 'Tinto'  , 14.0         , 'Este vino se añeja en barricas de roble francés durante un periodo de 10 meses.'                    , 'Un vino que celebra la riqueza y diversidad de los suelos latinoamericanos. Cerro Verde te envolverá con sus aromas intensos a frutas rojas y negras, su textura aterciopelada y su final persistente, transportándote a los majestuosos paisajes de los viñedos.' , 'Este vino chileno tiene un aroma a frutos rojos y negros, junto con notas de vainilla y especias. En boca, es un vino de cuerpo medio con taninos suaves y una acidez equilibrada, con sabores a frutos negros maduros y un toque de chocolate oscuro. El final es largo y agradable.'                                                                 , '16-18°C'          , 'Es ideal para acompañar con platos de carne de cerdo asada, carnes rojas a la parrilla y quesos suaves.' , 3           , true  , 178631   , 'https://npuxpuelimayqrsmzqur.supabase.co/storage/v1/object/public/images/178631.png' ,false    , 4        ),
    ('Codice'                                        , 4       , 2018 , 'Bodegas y Viñedos Codice, Argentina'        , 1               , 'Mendoza'               , 45.562  , 80   , 'Tinto'  , 13.5         , 'Este vino se añeja en barricas de roble francés durante un periodo de 12 meses.'                    , 'Descubre la esencia de la pasión y la historia en cada botella de Codice. Con sus notas a frutas maduras, su elegancia y su equilibrio perfecto, este vino te invita a disfrutar de una experiencia sensorial única que cautivará tus sentidos.'                   , 'De origen argentino, este vino tinto presenta un aroma a frutos rojos y negros, junto con notas de especias y cedro. En el paladar, es un vino de cuerpo medio con taninos suaves y una acidez equilibrada, con sabores a frutos negros y un toque de vainilla. El final es largo y agradable.'                                                        , '16-18°C'          , 'Va muy bien con platos de carnes rojas a la parrilla, guisos y estofados.'                               , 3           , true  , 265178   , 'https://npuxpuelimayqrsmzqur.supabase.co/storage/v1/object/public/images/265178.png' ,false    , 4        ),
    ('Vega Sicilia Único'                            , 1       , 2015 , 'Bodegas Vega Sicilia'                       , 'España'        , 'Ribera del Duero'      , 250     , 10   , 'Tinto'  , 14.5         , 'Roble francés'                                                                                      , 'Vega Sicilia Único es un vino emblemático de la bodega. Elaborado con uvas de la variedad Tempranillo, ofrece una gran estructura y complejidad aromática.'                                                                                                        , 'Notas de cata: Aromas a frutas negras maduras, especias y notas balsámicas. En boca es potente, con taninos suaves y equilibrados.'                                                                                                                                                                                                                    , '16-18°C'          , 'Ideal para carnes rojas asadas y quesos curados.'                                                        , 1           , true  ,          , ''                                                                                    ,false    , 4        ),
    ('Château Margaux'                               , 1       , 2016 , 'Château Margaux'                            , 'Francia'       , 'Burdeos'               , 500     , 5    , 'Tinto'  , 13.5         , 'Roble francés'                                                                                      , 'Château Margaux es un vino de renombre mundial. Elaborado con uvas de las variedades Cabernet Sauvignon, Merlot, Cabernet Franc y Petit Verdot, representa la elegancia y sofisticación de los vinos de Burdeos.'                                                  , 'Notas de cata: Aromas a frutas rojas, especias y cedro. En boca es sedoso, con taninos finos y buena estructura.'                                                                                                                                                                                                                                      , '18-20°C'          , 'Combina perfectamente con carnes de caza y quesos maduros.'                                              , 1           , true  ,          , ''                                                                                    ,false    , 4        ),
    ('Screaming Eagle'                               , 1       , 2017 , 'Screaming Eagle Winery'                     , 'Estados Unidos', 'Napa Valley'           , 3000    , 2    , 'Tinto'  , 14.8         , 'Roble francés'                                                                                      , 'Screaming Eagle es un vino icónico de California. Elaborado principalmente con uvas de la variedad Cabernet Sauvignon, es reconocido por su calidad excepcional y su producción limitada.'                                                                         , 'Notas de cata: Aromas intensos a frutas negras, cacao y vainilla. En boca es potente, con taninos sedosos y gran longitud.'                                                                                                                                                                                                                            , '18-20°C'          , 'Ideal para disfrutarlo solo o con carnes de alta calidad.'                                               , 1           , true  ,          , ''                                                                                    ,false    , 4        ),
    ('Champagne Krug Clos du Mesnil'                 , 1       , 2006 , 'Krug'                                       , 'Francia'       , 'Champagne'             , 1500    , 3    , 'Blanco' , 12.5         , 'Sin barrica'                                                                                        , 'Champagne Krug Clos du Mesnil es un champagne excepcional. Elaborado con uvas Chardonnay provenientes de un viñedo único, ofrece elegancia y finura.'                                                                                                              , 'Notas de cata: Aromas a frutas blancas, pan tostado y avellanas. En boca es cremoso, con una acidez equilibrada y un final largo.'                                                                                                                                                                                                                     , '8-10°C'           , 'Perfecto como aperitivo o para acompañar mariscos y pescados.'                                           , 2           , true  ,          , ''                                                                                    ,false    , 4        ),
    ('Penfolds Grange'                               , 1       , 2014 , 'Penfolds'                                   , 'Australia'     , 'South Australia'       , 350     , 8    , 'Tinto'  , 14.5         , 'Roble americano'                                                                                    , 'Penfolds Grange es uno de los vinos más prestigiosos de Australia. Elaborado con uvas de las variedades Shiraz y Cabernet Sauvignon, destaca por su concentración y complejidad.'                                                                                  , 'Notas de cata: Aromas intensos a frutas maduras, especias y chocolate. En boca es poderoso, con taninos firmes y gran estructura.'                                                                                                                                                                                                                     , '16-18°C'          , 'Ideal para carnes a la parrilla y platos condimentados.'                                                 , 1           , true  ,          , ''                                                                                    ,false    , 4        ),
    ('Château Lafite Rothschild'                     , 1       , 2010 , 'Château Lafite Rothschild'                  , 'Francia'       , 'Burdeos'               , 800     , 6    , 'Tinto'  , 13.5         , 'Roble francés'                                                                                      , 'Château Lafite Rothschild es uno de los cinco Premiers Grands Crus Classés de Burdeos. Elaborado con uvas Cabernet Sauvignon, Merlot, Cabernet Franc y Petit Verdot, es sinónimo de elegancia y longevidad.'                                                       , 'Notas de cata: Aromas a frutas negras, cedro y tabaco. En boca es refinado, con taninos sedosos y gran persistencia.'                                                                                                                                                                                                                                  , '18-20°C'          , 'Combina muy bien con carnes de caza y quesos añejos.'                                                    , 1           , true  ,          , ''                                                                                    ,false    , 4        ),
    ('Dom Pérignon'                                  , 1       , 2012 , 'Dom Pérignon'                               , 'Francia'       , 'Champagne'             , 200     , 12   , 'Blanco' , 12.5         , 'Sin barrica'                                                                                        , 'Dom Pérignon es uno de los champagnes más reconocidos del mundo. Elaborado con uvas Chardonnay y Pinot Noir, destaca por su elegancia y complejidad aromática.'                                                                                                    , 'Notas de cata: Aromas a frutas blancas, almendras y pan tostado. En boca es vibrante, con una acidez equilibrada y un final largo.'                                                                                                                                                                                                                    , '8-10°C'           , 'Perfecto como aperitivo o para acompañar mariscos y aves.'                                               , 2           , true  ,          , ''                                                                                    ,false    , 4        ),
    ('Opus One'                                      , 1       , 2016 , 'Opus One Winery'                            , 'Estados Unidos', 'Napa Valley'           , 400     , 4    , 'Tinto'  , 14.2         , 'Roble francés'                                                                                      , 'Opus One es un vino emblemático de California. Elaborado con uvas de las variedades Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot y Malbec, combina la elegancia del vino francés con la expresividad del Nuevo Mundo.'                                 , 'Notas de cata: Aromas a frutas negras, especias y tabaco. En boca es sedoso, con taninos finos y una estructura equilibrada.'                                                                                                                                                                                                                          , '16-18°C'          , 'Ideal para acompañar carnes a la parrilla y quesos semicurados.'                                         , 1           , true  ,          , ''                                                                                    ,false    , 4        ),
    ('La Rioja Alta Gran Reserva 904'                , 1       , 2011 , 'La Rioja Alta'                              , 'España'        , 'La Rioja'              , 80      , 15   , 'Tinto'  , 13.5         , 'Roble americano'                                                                                    , 'La Rioja Alta Gran Reserva 904 es un vino tradicional de La Rioja. Elaborado con uvas Tempranillo, ofrece elegancia y complejidad tras su larga crianza en barricas de roble.'                                                                                     , 'Notas de cata: Aromas a frutas maduras, especias y cuero. En boca es equilibrado, con taninos sedosos y un final persistente.'                                                                                                                                                                                                                         , '16-18°C'          , 'Perfecto para acompañar cordero asado y embutidos ibéricos.'                                             , 1           , true  ,          , ''                                                                                    ,false    , 4        ),
    ('Louis Roederer Cristal'                        , 1       , 2013 , 'Louis Roederer'                             , 'Francia'       , 'Champagne'             , 300     , 7    , 'Blanco' , 12.0         , 'Sin barrica'                                                                                        , 'Louis Roederer Cristal es un champagne de lujo. Elaborado con uvas Chardonnay y Pinot Noir, destaca por su frescura y elegancia, representando la excelencia en el arte del champagne.'                                                                            , 'Notas de cata: Aromas a frutas cítricas, florales y brioche. En boca es seductor, con una acidez vibrante y un final largo.'                                                                                                                                                                                                                           , '8-10°C'           , 'Ideal para maridar con mariscos y pescados finos.'                                                       , 2           , true  ,          , ''                                                                                    ,false    , 4        ),
    ('Malleolus de Valderramiro'                     , 1       , 2015 , 'Emilio Moro'                                , 'España'        , 'Ribera del Duero'      , 120     , 20   , 'Tinto'  , 14.0         , 'Roble francés'                                                                                      , 'Malleolus de Valderramiro es un vino de la prestigiosa bodega Emilio Moro. Elaborado con uvas de la variedad Tempranillo, muestra la esencia de la Ribera del Duero con su carácter frutal y estructura.'                                                          , 'Notas de cata: Aromas a frutas negras, especias y toques minerales. En boca es potente, con taninos maduros y una persistencia agradable.'                                                                                                                                                                                                             , '16-18°C'          , 'Combina muy bien con carnes rojas y quesos curados.'                                                     , 1           , true  ,          , ''                                                                                    ,false    , 4        ),
    ('Kendall-Jackson Vintner\'s Reserve Chardonnay' , 1       , 2019 , 'Kendall-Jackson'                            , 'Estados Unidos', 'California'            , 30      , 30   , 'Blanco' , 14.5         , 'Sin barrica'                                                                                        , 'Kendall-Jackson Vintner`s Reserve Chardonnay es un vino representativo de California. Elaborado con uvas Chardonnay, muestra una combinación de frutas tropicales y notas de roble bien integradas.'                                                               , 'Notas de cata: Aromas a piña, mango y vainilla. En boca es cremoso, con una acidez refrescante y un final persistente.'                                                                                                                                                                                                                                , '10-12°C'          , 'Ideal para maridar con aves, pescados grasos y pastas con salsas cremosas.'                              , 2           , true  ,          , ''                                                                                    ,false    , 4        ),
    ('Bollinger Special Cuvée'                       , 1       , NULL , 'Bollinger'                                  , 'Francia'       , 'Champagne'             , 70      , 25   , 'Blanco' , 12.0         , 'Sin barrica'                                                                                        , 'Bollinger Special Cuvée es un champagne de renombre. Elaborado con uvas Pinot Noir, Chardonnay y Pinot Meunier, destaca por su complejidad y elegancia.'                                                                                                           , 'Notas de cata: Aromas a frutas maduras, miel y tostadas. En boca es rico, con una burbuja fina y un final largo.'                                                                                                                                                                                                                                      , '8-10°C'           , 'Perfecto como aperitivo o para acompañar mariscos y quesos suaves.'                                      , 2           , true  ,          , ''                                                                                    ,false    , 4        );