-- Active: 1681022712039@@db.hijaeegxjbuivzckpijg.supabase.co@5432@postgres@pruebas
CREATE TABLE IF NOT EXISTS pruebas.secciones (
    ID BIGSERIAL PRIMARY KEY,
    nombre TEXT NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT false,
    id_unica TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS pruebas.usuarios (
    ID bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    usuario character varying(50),
    clave character varying(100),
    nombre character varying(50),
    apellido character varying(50),
    email character varying(100),
    rol character varying(20)
);

CREATE TABLE IF NOT EXISTS pruebas.vinos (
    -- id: Identificador único generado automáticamente por la base de datos para cada registro en la tabla
    ID SERIAL PRIMARY KEY,
    -- nombre: Nombre del vino, cadena de caracteres de longitud máxima de 255
    nombre VARCHAR(255) NOT NULL,
    -- variedad: Variedad de uva utilizada para elaborar el vino, cadena de caracteres de longitud máxima de 255
    variedad VARCHAR(255) NOT NULL,
    -- anada: Año de cosecha de la uva utilizada para elaborar el vino, número entero
    anada INTEGER,
    -- bodega: Nombre de la bodega o viñedo que produce el vino, cadena de caracteres de longitud máxima de 255
    bodega VARCHAR(255) NOT NULL,
    -- pais: País de origen del vino, cadena de caracteres de longitud máxima de 255
    pais VARCHAR(255) NOT NULL,
    -- region: Región vinícola donde se produce el vino, cadena de caracteres de longitud máxima de 255
    region VARCHAR(255) NOT NULL,
    -- precio: Precio del vino, número decimal con una precisión de 10 dígitos y una escala de 2 dígitos
    precio NUMERIC(10, 2),
    -- stock: Cantidad de botellas del vino que están disponibles en el inventario, número entero
    stock INTEGER,
    -- tipo: Tipo de vino (tinto, blanco, rosado, etc.), cadena de caracteres de longitud máxima de 255
    tipo VARCHAR(255),
    -- nivel_alcohol: Porcentaje de alcohol del vino, número decimal con una precisión de 3 dígitos y una escala de 1 dígito
    nivel_alcohol NUMERIC(3, 1),
    -- tipo_barrica: Tipo de barrica en la que se ha criado el vino (roble americano, roble francés, etc.), cadena de caracteres de longitud máxima de 255
    tipo_barrica VARCHAR(255),
    -- notas_cata: Descripción de las características de sabor, aroma, color y cuerpo del vino, campo de texto
    notas_cata TEXT,
    -- temperatura_consumo: Temperatura recomendada para servir el vino, cadena de caracteres de longitud máxima de 255
    temperatura_consumo VARCHAR(255),
    -- maridaje: Lista de platos recomendados para maridar con el vino, campo de texto
    maridaje TEXT,
    -- id_categoria: Identificador de la categoría a la que pertenece el vino, número entero
    id_categoria INTEGER,
    -- activo: Indica si el vino está activo o no, booleano con valor por defecto de false
    activo BOOLEAN NOT NULL DEFAULT false,
    -- id_imagen: Identificador de la imagen asociada al vino, número entero
    id_imagen INTEGER,
    -- promocion: Indica si el vino está en promoción o no, booleano con valor por defecto de false
    promocion BOOLEAN NOT NULL DEFAULT false
);

INSERT INTO pruebas.secciones (nombre, activo, id_unica)
VALUES
    ('NUESTROS VINOS MAS VENDIDOS', TRUE, '1'),
    ('NUESTROS MEJORES VINOS', TRUE, '2'),
    ('VINOS IMPORTADOS MAS EXQUISITOS', TRUE, '3'),
    ('PROMOCIONES', TRUE, '4');

INSERT INTO pruebas.usuarios (usuario, clave, nombre, apellido, email, rol)
VALUES
    (
        'persona_1',
        '12345678',
        'tienda',
        'online',
        'tienda@online.com',
        'Administrador'
    ),
    (
        'persona_2',
        '12345678',
        'Elizabeth',
        'Gottlieb',
        'Schuyler.Cronin@hotmail.com',
        'UsuarioCorriente'
    );

INSERT INTO pruebas.vinos 
    (nombre                                        ,variedad            ,anada,bodega                     ,pais            ,region            ,precio ,stock,tipo     ,nivel_alcohol,tipo_barrica               ,notas_cata                                                                                                                                                                                                                                                                                   ,temperatura_consumo                                                                                                                                                                                                                                                                                                                                                                                                                                                        ,maridaje,id_categoria,activo ,id_imagen                                                                             ,promocion, busqueda)
    ('Vega Sicilia Único'                          ,'Tinto Reserva'     ,2010 ,'Bodegas Vega Sicilia'     ,'España'        ,'Ribera del Duero',399.99 ,10   ,'Vino'   ,14.5         ,'Roble francés y americano','Vega Sicilia Único es un vino tinto reserva de España producido por la prestigiosa bodega Vega Sicilia. Este vino se caracteriza por su elegancia, complejidad y gran potencial de guarda. Es considerado como uno de los mejores vinos de España y del mundo.'                             ,'En la cata, Vega Sicilia Único muestra un color rojo picota intenso. En nariz, se aprecian aromas intensos de frutas negras, especias, tabaco, cuero y notas balsámicas. En boca, es un vino estructurado y equilibrado, con sabores a frutas maduras, chocolate, vainilla y un final largo y persistente. Se recomienda decantar antes de servir. Es ideal para maridar con carnes rojas y quesos curados.'                                                              ,5       ,true        ,192837 ,'https://npuxpuelimayqrsmzqur.supabase.co/storage/v1/object/public/images/192837.png' ,true     ,4        ),
    ('Château Margaux'                             ,'Tinto Gran Reserva',2015 ,'Château Margaux'          ,'Francia'       ,'Burdeos'         ,799.99 ,5    ,'Vino'   ,13.5         ,'Roble francés'            ,'Château Margaux es un vino tinto gran reserva de Francia producido por el prestigioso Château Margaux. Este vino se caracteriza por su elegancia, finura y complejidad aromática. Es considerado como uno de los mejores vinos de Burdeos y del mundo.'                                     ,'En la cata, Château Margaux muestra un color rojo rubí profundo. En nariz, se aprecian aromas intensos de frutas rojas, flores, cedro, tabaco y especias. En boca, es un vino sedoso y equilibrado, con sabores a frutas maduras, regaliz, vainilla y un final largo y elegante. Se recomienda decantar antes de servir. Es ideal para maridar con carnes de caza y quesos añejos.'                                                                                       ,5       ,true        ,354621 ,'https://npuxpuelimayqrsmzqur.supabase.co/storage/v1/object/public/images/354621.png' ,true     ,4        ),
    ('Screaming Eagle'                             ,'Tinto'             ,2016 ,'Screaming Eagle Winery'   ,'Estados Unidos','California'      ,2999.99,3    ,'Vino'   ,14.5         ,'Roble francés'            ,'Screaming Eagle es un vino tinto de lujo producido por la reconocida bodega Screaming Eagle Winery en California, Estados Unidos. Este vino se caracteriza por su exclusividad, intensidad y calidad excepcional. Es considerado como uno de los vinos más caros y buscados del mundo.'     ,'En la cata, Screaming Eagle muestra un color rojo oscuro e intenso. En nariz, se aprecian aromas complejos de frutas negras, violetas, chocolate, especias y notas minerales. En boca, es un vino potente y concentrado, con sabores a frutas maduras, regaliz, café, tostado y un final largo y sedoso. Se recomienda decantar antes de servir. Es ideal para maridar con carnes de caza y platos gourmet.'                                                             ,5       ,true        ,678912 ,'https://npuxpuelimayqrsmzqur.supabase.co/storage/v1/object/public/images/678912.png' ,true     ,4        ),
    ('Champagne Krug Clos du Mesnil'               ,'Espumoso'          ,2006 ,'Krug'                     ,'Francia'       ,'Champagne'       ,1999.99,2    ,'Champán',12.5         ,'Sin roble'                ,'Champagne Krug Clos du Mesnil es un espumoso de lujo producido por la prestigiosa casa de champán Krug. Este champán se caracteriza por su exclusividad, elegancia y gran potencial de guarda. Es considerado como uno de los mejores champagnes del mundo.'                                ,'En la cata, Champagne Krug Clos du Mesnil muestra un color amarillo dorado brillante con reflejos verdosos. En nariz, se aprecian aromas intensos de frutas blancas, flores, brioche, avellanas y notas minerales. En boca, es un champán fresco y cremoso, con sabores a frutas maduras, pan tostado, almendras y una acidez equilibrada. Se recomienda servir frío. Es ideal para disfrutarlo solo o para maridar con mariscos y pescados.'                             ,5       ,true        ,987654 ,'https://npuxpuelimayqrsmzqur.supabase.co/storage/v1/object/public/images/987654.png' ,true     ,4        ),
    ('Penfolds Grange'                             ,'Tinto'             ,2012 ,'Penfolds'                 ,'Australia'     ,'Barossa Valley'  ,799.99 ,7    ,'Vino'   ,14.5         ,'Roble americano y francés','Penfolds Grange es un vino tinto de Australia producido por la reconocida bodega Penfolds. Este vino se caracteriza por su calidad excepcional, complejidad y gran potencial de guarda. Es considerado como uno de los mejores vinos de Australia y del mundo.'                             ,'En la cata, Penfolds Grange muestra un color rojo oscuro e intenso. En nariz, se aprecian aromas concentrados de frutas negras, especias, chocolate, tabaco y notas tostadas. En boca, es un vino potente y estructurado, con sabores a frutas maduras, café, vainilla y un final largo y persistente. Se recomienda decantar antes de servir. Es ideal para maridar con carnes a la parrilla y quesos añejos.'                                                           ,5       ,true        ,564738 ,'https://npuxpuelimayqrsmzqur.supabase.co/storage/v1/object/public/images/564738.png' ,true     ,4        ),
    ('Château Lafite Rothschild'                   ,'Tinto Reserva'     ,2010 ,'Château Lafite Rothschild','Francia'       ,'Burdeos'         ,999.99 ,4    ,'Vino'   ,13.5         ,'Roble francés'            ,'Château Lafite Rothschild es un vino tinto reserva de Francia producido por el renombrado Château Lafite Rothschild. Este vino se caracteriza por su elegancia, refinamiento y capacidad de envejecimiento. Es considerado como uno de los mejores vinos de Burdeos y del mundo.'           ,'En la cata, Château Lafite Rothschild muestra un color rojo rubí profundo y brillante. En nariz, se aprecian aromas complejos de frutas rojas, cedro, cassis, grafito y notas especiadas. En boca, es un vino estructurado y equilibrado, con sabores a frutas maduras, regaliz, tabaco, vainilla y un final largo y sedoso. Se recomienda decantar antes de servir. Es ideal para maridar con carnes rojas y platos de caza.'                                            ,5       ,true        ,213546 ,'https://npuxpuelimayqrsmzqur.supabase.co/storage/v1/object/public/images/213546.png' ,true     ,4        ),
    ('Dom Pérignon'                                ,'Espumoso'          ,2010 ,'Moët & Chandon'           ,'Francia'       ,'Champagne'       ,299.99 ,10   ,'Champán',12.5         ,'Sin roble'                ,'Dom Pérignon es un espumoso de prestigio producido por la famosa casa de champán Moët & Chandon. Este champán se caracteriza por su elegancia, frescura y capacidad de guarda. Es considerado como uno de los mejores champagnes del mundo.'                                                ,'En la cata, Dom Pérignon muestra un color amarillo dorado con reflejos verdosos. En nariz, se aprecian aromas intensos de frutas blancas, flores blancas, almendras, brioche y notas tostadas. En boca, es un champán fresco y cremoso, con sabores a frutas maduras, pan tostado, avellanas y una acidez equilibrada. Se recomienda servir frío. Es ideal para ocasiones especiales y marida bien con mariscos y pescados.'                                              ,5       ,true        ,876543 ,'https://npuxpuelimayqrsmzqur.supabase.co/storage/v1/object/public/images/876543.png' ,true     ,4        ),
    ('Opus One'                                    ,'Tinto'             ,2017 ,'Opus One Winery'          ,'Estados Unidos','California'      ,499.99 ,8    ,'Vino'   ,14.5         ,'Roble francés'            ,'Opus One es un vino tinto de lujo producido por la reconocida Opus One Winery en California, Estados Unidos. Este vino se caracteriza por su elegancia, complejidad y calidad excepcional. Es considerado como uno de los mejores vinos de California y del mundo.'                         ,'En la cata, Opus One muestra un color rojo oscuro e intenso. En nariz, se aprecian aromas concentrados de frutas negras, especias, cedro, vainilla y notas florales. En boca, es un vino estructurado y equilibrado, con sabores a frutas maduras, chocolate, tabaco y un final largo y sedoso. Se recomienda decantar antes de servir. Es ideal para maridar con carnes a la parrilla y quesos curados.'                                                                 ,5       ,true        ,987654 ,'https://npuxpuelimayqrsmzqur.supabase.co/storage/v1/object/public/images/987654.png' ,true     ,4        ),
    ('La Rioja Alta Gran Reserva 904'              ,'Tinto Gran Reserva',2011 ,'La Rioja Alta'            ,'España'        ,'Rioja'           ,149.99 ,15   ,'Vino'   ,13.5         ,'Roble americano'          ,'La Rioja Alta Gran Reserva 904 es un vino tinto gran reserva de España producido por la reconocida bodega La Rioja Alta. Este vino se caracteriza por su elegancia, finura y gran potencial de guarda. Es considerado como uno de los mejores vinos de Rioja y del mundo.'                  ,'En la cata, La Rioja Alta Gran Reserva 904 muestra un color rojo rubí con reflejos teja. En nariz, se aprecian aromas complejos de frutas maduras, vainilla, especias, tabaco y notas balsámicas. En boca, es un vino equilibrado y sedoso, con sabores a frutas rojas, regaliz, cacao, tostado y un final largo y elegante. Se recomienda decantar antes de servir. Es ideal para maridar con carnes asadas y quesos añejos.'                                            ,5       ,true        ,765432 ,'https://npuxpuelimayqrsmzqur.supabase.co/storage/v1/object/public/images/765432.png' ,true     ,4        ),
    ('Louis Roederer Cristal'                      ,'Espumoso'          ,2012 ,'Louis Roederer'           ,'Francia'       ,'Champagne'       ,299.99 ,10   ,'Champán',12.5         ,'Sin roble'                ,'Louis Roederer Cristal es un espumoso de prestigio producido por la reconocida casa de champán Louis Roederer. Este champán se caracteriza por su elegancia, frescura y gran potencial de guarda. Es considerado como uno de los mejores champagnes del mundo.'                             ,'En la cata, Louis Roederer Cristal muestra un color amarillo dorado brillante con reflejos verdosos. En nariz, se aprecian aromas intensos de frutas blancas, cítricos, almendras, brioche y notas tostadas. En boca, es un champán fresco y cremoso, con sabores a frutas maduras, pan tostado, avellanas y una acidez equilibrada. Se recomienda servir frío. Es ideal para ocasiones especiales y marida bien con mariscos y pescados.'                                ,5       ,true        ,234567 ,'https://npuxpuelimayqrsmzqur.supabase.co/storage/v1/object/public/images/234567.png' ,true     ,4        ),
    ('Malleolus de Valderramiro'                   ,'Tinto Reserva'     ,2014 ,'Bodegas Emilio Moro'      ,'España'        ,'Ribera del Duero',129.99 ,12   ,'Vino'   ,14.5         ,'Roble francés'            ,'Bodegas Emilio Moro Malleolus de Valderramiro es un vino tinto reserva de España producido por la reconocida bodega Bodegas Emilio Moro. Este vino se caracteriza por su intensidad, complejidad y elegancia. Es considerado como uno de los mejores vinos de Ribera del Duero y del mundo.','En la cata, Bodegas Emilio Moro Malleolus de Valderramiro muestra un color rojo picota intenso con reflejos violáceos. En nariz, se aprecian aromas concentrados de frutas negras, especias, tostado, chocolate y notas minerales. En boca, es un vino estructurado y equilibrado, con sabores a frutas maduras, regaliz, café, vainilla y un final largo y persistente. Se recomienda decantar antes de servir. Es ideal para maridar con carnes rojas y quesos curados.',5       ,true        ,876543 ,'https://npuxpuelimayqrsmzqur.supabase.co/storage/v1/object/public/images/876543.png' ,true     ,4        ),
    ('Kendall-Jackson Vintner`s Reserve Chardonnay','Blanco'            ,2019 ,'Kendall-Jackson'          ,'Estados Unidos','California'      ,24.99  ,20   ,'Vino'   ,13.5         ,'Sin roble'                ,'Kendall-Jackson Vintner\'s Reserve Chardonnay es un vino blanco de California, Estados Unidos, producido por Kendall-Jackson. Este vino se caracteriza por su frescura, equilibrio y notas frutales. Es considerado como uno de los mejores vinos blancos de California.'                   ,'En la cata, Kendall-Jackson Vintner\'s Reserve Chardonnay muestra un color amarillo brillante con reflejos verdosos. En nariz, se aprecian aromas intensos de frutas tropicales, cítricos, melocotón y notas florales. En boca, es un vino suave y cremoso, con sabores a frutas maduras, vainilla, mantequilla y una acidez equilibrada. Se recomienda servir frío. Es ideal para maridar con mariscos, aves y ensaladas.'                                               ,5       ,true        ,345678 ,'https://npuxpuelimayqrsmzqur.supabase.co/storage/v1/object/public/images/345678.png' ,true     ,4        ),
    ('Bollinger Special Cuvée'                     ,'Espumoso'          ,NV   ,'Bollinger'                ,'Francia'       ,'Champagne'       ,59.99  ,25   ,'Champán',12           ,'Sin roble'                ,'Bollinger Special Cuvée es un espumoso de prestigio producido por la reconocida casa de champán Bollinger. Este champán se caracteriza por su elegancia, complejidad y calidad constante. Es considerado como uno de los mejores champagnes del mundo.'                                     ,'En la cata, Bollinger Special Cuvée muestra un color amarillo dorado con reflejos verdosos. En nariz, se aprecian aromas intensos de frutas maduras, pan tostado, avellanas, especias y notas de levadura. En boca, es un champán estructurado y equilibrado, con sabores a frutas blancas, pan tostado, miel y una acidez vibrante. Se recomienda servir frío. Es ideal para celebraciones y marida bien con mariscos y platos gourmet.'                                 ,5       ,true        ,456789 ,'https://npuxpuelimayqrsmzqur.supabase.co/storage/v1/object/public/images/456789.png' ,true     ,4        );